ALTER TABLE users ADD COLUMN address_line1 VARCHAR(300);
ALTER TABLE users ADD COLUMN address_line2 VARCHAR(300);
ALTER TABLE users ADD COLUMN city VARCHAR(120);
ALTER TABLE users ADD COLUMN postal_code VARCHAR(32);
ALTER TABLE users ADD COLUMN country VARCHAR(80);
ALTER TABLE users ADD COLUMN phone VARCHAR(40);
ALTER TABLE users ADD COLUMN billing_full_name VARCHAR(200);
